src/Theatrum.Web.Razor/Controllers/Admin/UsersAdminController.cs
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers.Admin
{
    [Route("admin/users")]

    [Authorize(Roles = Roles.Admin)]
    public class UsersAdminController : Controller
    {
        private readonly IUserService _userService;
        private readonly PaginationConfig _paginationConfig;

        public UsersAdminController(IUserService userService,
            IOptions<PaginationConfig> paginationConfig)
        {
            _userService = userService;
            _paginationConfig = paginationConfig.Value;
        }

        [Route("Index")]
        public async Task<IActionResult> Index(UserFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        {
            var result = await Theatrs(filteringAdminModel, page, nameof(Index));
            return View(result);
        }
        private async Task<UserFilteringAdminModel> Theatrs(UserFilteringAdminModel filteringAdminModel, int page, string actionName)
        {
            if (filteringAdminModel.FilteringSettings == null)
            {
                filteringAdminModel.FilteringSettings = new UserFilteringSettingsAdminModel();
            }

            var count = await _userService.GetAllCount(filteringAdminModel.FilteringSettings);

            var users =
                await _userService.GetAllPaginated(filteringAdminModel.FilteringSettings,
                    _paginationConfig.PaginationAdminPageSize * (page - 1),
                    _paginationConfig.PaginationAdminPageSize);

            UserFilteringAdminModel theatrsFilteringAdminModel = new UserFilteringAdminModel()
            {
                Users = new GenericPaginatedModel<AppUserModel>()
                {
                    Models = users,
                    Pagination = new PaginationAdminModel(count, page,
                        _paginationConfig.PaginationAdminPageSize, actionName),
                },
                FilteringSettings = filteringAdminModel.FilteringSettings,
            };
            return theatrsFilteringAdminModel;
        }

        [HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var theatr = await _userService.GetById((Guid)id);
            if (theatr == null)
            {
                return NotFound();
            }

            return View(theatr);
        }

        [HttpPost, Route("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _userService.DeleteById((Guid)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Theatrum.Web.Razor/Views/UsersAdmin/Delete.cshtml
@model Theatrum.Models.Models.AppUserModel
@{
  ViewData["Title"] = "Delete";
  Layout = "_LayoutAdminPages";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
  <h4>User</h4>
  <hr />
  <dl class="row">
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.UserName)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.UserName)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Email)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.RegistrationDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.RegistrationDate)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.BirthdayDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.BirthdayDate)
    </dd>
  </dl>

  <form asp-controller="UsersAdmin" asp-action="DeleteConfirmed">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
  </form>
</div>

src/Theatrum.Web.Razor/Views/UsersAdmin/Index.cshtml
@model Theatrum.Models.Admin.UserFilteringAdminModel

@{
  ViewData["Title"] = "Index";
  Layout = "_LayoutAdminPages";
}

<h1>Theatrs</h1>

<form asp-controller="UsersAdmin" asp-action="Index" method="post">
  <div class="form-group row">
    <label asp-for="FilteringSettings.UserName" class="col-sm-1 col-form-label">UserName</label>
    <div class="col-sm-3">
      <input asp-for="FilteringSettings.UserName" class="form-control" />
    </div>
    <label asp-for="FilteringSettings.Email" class="col-sm-1 col-form-label">Email</label>
    <div class="col-sm-3">
      <input asp-for="FilteringSettings.Email" class="form-control" />
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </div>
</form>


@if (Model.Users.Models.Count != 0)
{
  <table class="table">
    <thead>
      <tr>
        <th>
          @Html.DisplayNameFor(model => model.Users.Models[0].Id)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Users.Models[0].Email)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Users.Models[0].UserName)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Users.Models[0].RegistrationDate)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Users.Models[0].BirthdayDate)
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model.Users.Models)
      {
        <tr>
          <td>
            @Html.DisplayFor(modelItem => item.Id)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.Email)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.UserName)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.BirthdayDate)
          </td>
          <td>
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
          </td>
        </tr>
      }
    </tbody>
  </table>
}