src/Theatrum.Web.Razor/Controllers/PhotoController.cs
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Models;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers
{
    [Route("photo")]
    public class PhotoController : Controller
    {
        private readonly IPhotoService _photoService;
        private readonly IWebHostEnvironment _env;

        public PhotoController(IPhotoService photoService,
            IWebHostEnvironment env)
        {
            _photoService = photoService;
            _env = env;
        }

        [HttpGet]
        [Route("AdminPhoto/{photoId}")]
        public async Task<FileResult> AdminPhoto(Guid? photoId)
        {
            if (photoId == null || photoId == Guid.Empty)
            {
                return await DefaultPhoto();
            }
            PhotoModel photo = await _photoService.GetPhoto((Guid)photoId);
            var filePath = Path.Combine(
                _env.ContentRootPath, Settings.UploadDirectory, photo.Name);
            if (!System.IO.File.Exists(filePath))
            {
                return await DefaultPhoto();
            }
            return PhysicalFile(filePath, photo.ContentType);

        }

        public async Task<FileResult> DefaultPhoto()
        {
            var filePath = Path.Combine(
                _env.ContentRootPath, Settings.UploadDirectory, "default.jpg");
            return PhysicalFile(filePath, "image/jpg");
        }

    }
}

src/Theatrum.Web.Razor/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using QRCoder;
using Theatrum.Bl.Abstract.IServices;
using Theatrum.Dal.Impl.Postgres;
using Theatrum.Entities.Entities;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers
{
    [Route("show")]
    public class ShowsController : Controller
    {
        private readonly IShowService _showService;
        private readonly UserManager<AppUser> _userManager;
        private readonly PaginationConfig _paginationConfig;

        public ShowsController(IShowService showService,
            IOptions<PaginationConfig> paginationConfig,
            UserManager<AppUser> userManager)
        {
            _showService = showService;
            _userManager = userManager;
            _paginationConfig = paginationConfig.Value;
        }

        //public async Task<IActionResult> Shows(ShowFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        //{
        //    var result = await Shows(filteringAdminModel, page, nameof(Shows));
        //    return View(result);
        //}

        //private async Task<ShowFilteringAdminModel> Shows(ShowFilteringAdminModel filteringAdminModel, int page, string actionName)
        //{
        //    if (filteringAdminModel.FilteringSettings == null)
        //    {
        //        filteringAdminModel.FilteringSettings = new ShowFilteringSettingsAdminModel();
        //    }

        //    var count = await _showService.GetAllCount(filteringAdminModel.FilteringSettings);

        //    var shows =
        //        await _showService.GetAllPaginated(filteringAdminModel.FilteringSettings,
        //            _paginationConfig.PaginationAdminPageSize * (page - 1),
        //            _paginationConfig.PaginationAdminPageSize);

        //    ShowFilteringAdminModel showsFilteringAdminModel = new ShowFilteringAdminModel()
        //    {
        //        Shows = new GenericPaginatedModel<ShowModel>()
        //        {
        //            Models = shows,
        //            Pagination = new PaginationAdminModel(count, page,
        //                _paginationConfig.PaginationAdminPageSize, actionName),
        //        },
        //        FilteringSettings = filteringAdminModel.FilteringSettings,
        //    };
        //    return showsFilteringAdminModel;
        //}

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Details([FromRoute] Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var theatr = await _showService.GetById((Guid)id);
            return View(theatr);
        }


        [HttpGet]
        [Authorize]
        [Route("tickets/{id}")]
        public async Task<IActionResult> Tickets([FromRoute] Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            List<PlaceModel> places = await _showService.GetPlacesBySessionId((Guid)id);
            return View(((Guid)id,places));
        }

        [Authorize]
        [Route("BuyTickets")]
        public async Task<IActionResult> BuyTickets(Guid sessionId, List<string> tickets, int price)
        {
            // Guid userId = (await _userManager.FindByNameAsync(User?.Identity?.Name)).Id;
            // List<PlaceModel> result = await _showService.CreateTickets(tickets, userId, sessionId);
            // for (int i = 0; i < result.Count; i++)
            // {
            //     result[i].QrCode = await GetQrCode(result[i].SecurityKey.ToString(), Color.Black);
            // }
            return View((sessionId,tickets, price));
        }

        [Authorize]
        [Route("BoughtTicket")]
        public async Task<IActionResult> BoughtTickets(Guid sessionId, List<string> tickets, [Required]string card, [Required]string date, [Required]string cvv)
        {
            Guid userId = (await _userManager.FindByNameAsync(User?.Identity?.Name)).Id;
            List<PlaceModel> result = await _showService.CreateTickets(tickets, userId, sessionId);
            return View(result);
        }

        public async Task<Byte[]> GetQrCode(string qrCodeText, Color color)
        {
            // using static method as instance method was just redirection to static one
            QRCodeData qrCodeData = QRCodeGenerator.GenerateQrCode(qrCodeText, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(4);
            if (color != Color.Black)
            {
                qrCodeImage = ChangeColor(qrCodeImage, color);
            }
            return BitmapToBytes(qrCodeImage);
        }

        private static Byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }

        private Bitmap ChangeColor(Bitmap scrBitmap, Color newColor)
        {
            // make an empty bitmap the same size as scrBitmap  
            Bitmap newBitmap = new Bitmap(scrBitmap.Width, scrBitmap.Height);
            for (int i = 0; i < scrBitmap.Width; i++)
            {
                for (int j = 0; j < scrBitmap.Height; j++)
                {
                    // get the pixel from the scrBitmap image  
                    var actualColor = scrBitmap.GetPixel(i, j);

                    // invert colors, since we want to tint the dark parts and not the bright ones
                    var invertedOriginalR = 255 - actualColor.R;
                    var invertedOriginalG = 255 - actualColor.G;
                    var invertedOriginalB = 255 - actualColor.B;

                    // multiply source by destination color (as float channels)
                    int r = (invertedOriginalR / 255) * (newColor.R / 255) * 255;
                    int g = (invertedOriginalG / 255) * (newColor.G / 255) * 255;
                    int b = (invertedOriginalB / 255) * (newColor.B / 255) * 255;
                    var tintedColor = Color.FromArgb(r, g, b);
                    newBitmap.SetPixel(i, j, tintedColor);
                }
            }
            return newBitmap;
        }
    }
}

src/Theatrum.Web.Razor/Views/Shows/BoughtTickets.cshtml
@model List<Theatrum.Models.Models.PlaceModel>
@{
  ViewData["Title"] = "Білети";
  Layout = "_Layout";
}


<button id='print_btn' class="waves-effect waves-light btn"><i class="large material-icons">local_printshop</i> Надрукувати білети</button>

<div id="tickets">
  @foreach (var item in @Model)
  {
    <p>Білет № @item.Id</p>
    <img style="margin-left: 10%; max-width: 20rem; min-width: 5rem; height: auto;" src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=@(item.SecurityKey)" />
    <h4>Місце:⠀@item.PlaceId.Split('_')[1]</h4>
    <h4>Ряд:⠀@item.PlaceId.Split('_')[3]</h4>}
</div>


<script type="text/javascript">

  document.getElementById("print_btn").onclick = 
  function printArea() {
    window.print();
    return false;
  }
</script>

src/Theatrum.Web.Razor/Views/Shows/BuyTickets.cshtml
@model (Guid, List<string>,int)
@{
  ViewData["Title"] = "Платіжні данні";
  Layout = "_Layout";
}

<h2>До сплати @(Model.Item3) грн.</h2>

<form class="col s12 truncate offset-s3"
      asp-action="BoughtTickets">
  @foreach (var i in Model.Item2)
  {
    <input hidden name="tickets" value="@i" />
  }
  <input hidden name="sessionId" value="@Model.Item1" />

  <div class="row">
    <div class="input-field col s4">
      <input id="card" type="text" class="validate" name="card">
      <label for="card">Номер картки</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s2">
      <input id="date" type="text" class="validate" placeholder="MM/YY" name="date">
      <label for="date">Дата</label>
    </div>
    <div class="input-field col s2">
      <input id="cvv" type="password" class="validate" placeholder="XXX" name="cvv">
      <label for="cvv">CVV</label>
    </div>
  </div>

  <button id="submit" type="submit" class=" btn waves-effect waves-light">Оплатити</button>
</form>

<script>
  document.getElementById("date").oninput = function (e) {

    var d = Number(e.data).toString();
    if (e.data != Number(e.data).toString()) {
      this.value = this.value.replace(e.data,"");
    }

    if (this.value.length === 5) {
      $('#cvv').focus();
    }

    if (this.value.length > 5) {
      this.value = e.data;
    }

    if (this.value.length === 2 && !this.value.includes('/')) {
      this.value += '/';
    }

  }

  document.getElementById("card").oninput = function (e) {

    var d = Number(e.data).toString();
    if (e.data != Number(e.data).toString()) {
      this.value = this.value.replace(e.data, "");
    }

    if (this.value.length === 16) {
      $('#date').focus();
    }

    if (this.value.length > 16) {
      this.value = e.data;
    }
  }

  document.getElementById("cvv").oninput = function (e) {

    var d = Number(e.data).toString();
    if (e.data != Number(e.data).toString()) {
      this.value = this.value.replace(e.data, "");
    }

    if (this.value.length === 3) {
      $('#submit').focus();
    }

    if (this.value.length > 3) {
      this.value = e.data;
    }
  }
</script>

src/Theatrum.Web.Razor/Views/Shows/Details.cshtml
@using Theatrum.Web.Razor.Helpers
@model Theatrum.Models.Models.ShowModel

@{
  ViewData["Title"] = Model.Name;
  ViewData["Meta.keywords"] = new string[]
  {
    $"Купити квиток на виставу Teatrum | {Model.Name}", $"придбати білет на виставу Teatrum | {Model.Name}", $"квитки Teatrum | {Model.Name}", $"Teatrum | *дата* театр",$"Teatrum |  {Model.Name} прем’єра", $"theatrum Teatrum |  {Model.Name}"
  };
  ViewData["Meta.description"] = @Model.Description;
  Layout = "_Layout";
}

<div class="col s3">
  <div id="imgThumbnail">
    <img class="materialboxed responsive-img" src="@(Url.ActionLink("AdminPhoto","Photo")+$"/{Model.PhotoId}")" alt="Here have to be thumbnail" style="vertical-align: top">
  </div>


</div>

<div class="col s9" style="padding-left: 5%">
  <div class="card grey darken-3">
    <div class="card-content white-text">
      <span class="card-title">Show Title</span>
      <div id="table" style="padding-top: 1%; padding-bottom: 2%">
        <table>
          <tbody>
            <tr>
              <td>Назва: </td>
              <td>@Model.Name</td>
            </tr>
            <tr>
              <td>Вік: </td>
              <td>@Model.AgeLimitation+</td>
            </tr>
            <tr>
              <td>Дати: </td>
              <td>@Html.NormalizeDate(Model.StartDate) - @Html.NormalizeDate(Model.EndDate)</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>@Model.Description</p>
    </div>
    <div class="card-action">
      <div>
        <div class="collection collection-no-borders">

          @if (Model.Sessions.Any())
          {
            @foreach (var s in Model.Sessions)
            {
              if (s.PlacesCount < 279)
              {
                <a asp-controller="Shows" asp-action="Tickets" asp-route-id="@s.Id" class="collection-item tooltipped collection-item-no-borders date grey darken-3" data-position="top" data-tooltip="@(279 - s.PlacesCount) вільних місць">@Html.NormalizeDate(s.StartDate) : @Html.NormalizeTime(s.StartDate)</a>
              }
            }
          }
        </div>
      </div>

    </div>
  </div>
</div>

src/Theatrum.Web.Razor/Views/Shows/Shows.cshtml
@model Theatrum.Models.Admin.ShowFilteringAdminModel

@{
    ViewData["Title"] = "Всі вистави";
    ViewData["Meta.keywords"] = new string[]
    {
    $"Квитки в театр", $"Театр Київ", $"Придбати білети на виставу", $"Teatrum"
    };
    ViewData["Meta.description"] = "Придбання квитків у всіх театрах києва на найближчі вистави.";
    Layout = "_Layout";
}

<h1>Вистави</h1>


<div class="col s3">
  <div id="imgThumbnail">
    <img class="materialboxed responsive-img" src="testPicture.jpg" alt="Here have to be thumbnail" style="vertical-align: top">

  </div>


</div>

<div class="col s9" style="padding-left: 5%">
  <div class="card grey darken-3">
    <div class="card-content white-text">
      <span class="card-title">Show Title</span>
      <div id="table" style="padding-top: 1%; padding-bottom: 2%">
        @if (Model.Shows.Models.Count != 0)
        {
          <table class="table">
            <thead>
              <tr>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].TheatrumId)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].Name)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].Description)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].StartDate)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].EndDate)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].AgeLimitation)
                </th>
                <th>
                  @Html.DisplayNameFor(model => model.Shows.Models[0].PhotoId)
                </th>
              </tr>
            </thead>
            <tbody>
              @foreach (var item in Model.Shows.Models)
              {
                <tr>
                  <td>
                    @Html.DisplayFor(modelItem => item.TheatrumId)
                  </td>
                  <td>
                    @Html.DisplayFor(modelItem => item.Name)
                  </td>
                  <td>
                    @Html.DisplayFor(modelItem => item.Description)
                  </td>
                  <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                  </td>
                  <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                  </td>
                  <td>
                    @Html.DisplayFor(modelItem => item.AgeLimitation)
                  </td>
                  <td>
                    @if (item.PhotoId != null)
                    {
                      <img class="image-small render-photo" href="" name=@Html.Raw(@Url.Action("AdminPhoto", "Photo", new {photoId = @item.PhotoId}))/>
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
        }
        @*<table>
          <tbody>
            <tr>
              <td>Age: </td>
              <td>...</td>

            </tr>
            <tr>
              <td>Year: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Original Name: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Director: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Rental period: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Language: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Genre: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Duration: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Production: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Studio: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Screenplay: </td>
              <td>...</td>
            </tr>
            <tr>
              <td>Starring: </td>
              <td>...</td>
            </tr>
          </tbody>
        </table>*@
      </div>
      <p>Descrition</p>
    </div>
    <div class="card-action">
      <!--
                             <span class="hint white-text translucent-1p">Choose date and time of the show to see if there are any free places</span>
                              <div class="row">
                                  <select class="col s6 browser-default grey darken-3 white-text" style="padding-right: 1%">
                                      <option value="" disabled selected>Choose date</option>
                                      <option value="1">Option 1</option>
                                      <option value="2">Option 2</option>
                                      <option value="3">Option 3</option>
                                  </select>
                                  <select class="col s6 browser-default grey darken-3 white-text">
                                      <option value="" disabled selected>Choose time</option>
                                      <option value="1">Option 1</option>
                                      <option value="2">Option 2</option>
                                      <option value="3">Option 3</option>
                                  </select>
                              </div>
                              <div class="row">
                                 <div class="col s6">
                                     <span class="white-text">Number of free places: 0 </span>
                                 </div>
                                  <button id="btnGoToPoster" class="btn waves-effect waves-light disabled" type="submit" name="action">Go buy tickets
                                      <i class="material-icons right">send</i>
                                  </button>
                              </div>
      -->
      <div>
        <div class="collection">
          <a href="#!" class="collection-item tooltipped date grey darken-3" data-position="top" data-tooltip="0 free places">FirstDate: timeOfBeginnig - timeOfEnding</a>
          <a href="#!" class="collection-item tooltipped date grey darken-3" data-position="top" data-tooltip="0 free places">SecondDate: timeOfBeginnig - timeOfEnding</a>
          <a href="#!" class="collection-item tooltipped date grey darken-3" data-position="top" data-tooltip="0 free places">ThirdDate: timeOfBeginnig - timeOfEnding</a>
        </div>
      </div>

    </div>
  </div>
</div>

src/Theatrum.Web.Razor/Views/Shows/Tickets.cshtml
@model (Guid, List<Theatrum.Models.Models.PlaceModel>)
@{
    ViewData["Title"] = "Зала вистави";

    // ViewData["Meta.keywords"] = new string[]
    // {
    // $"Купити квиток на виставу Teatrum | {Model.Name}", $"придбати білет на виставу Teatrum | {Model.Name}", $"квитки Teatrum | {Model.Name}", $"Teatrum | *дата* театр",$"Teatrum |  {Model.Name} прем’єра", $"theatrum Teatrum |  {Model.Name}"
    // };
    // ViewData["Meta.description"] = @Model.Description;
    Layout = "_Layout";
}

@{ await Html.RenderPartialAsync("_PlacesPartial"); }

<div class="col s12 ">
  <div style="background-color: #212121; border-radius: 10px; height: 50vh;">
    <div class="s-vflex full-height">
      <div class="container">
      </div>
      <div class="container">
        <div id="btnPay" class="s-vflex-center">
          <span class=" weight-strong white-text">Всього до сплати: </span>
          <span class="summary white-text translucent"> <span id="generalPrice">0</span> грн </span>
          <div href="#" class="s-vflex"
               style="display: flex; height: auto; padding: 0 32px; padding-top: 5%">
            <a id="pay-tickets" href="#" type="button" class="indigo darken-4 btn waves-effect waves-dark" onclick="onSubmitTickents()">
              Сплатити
            </a>
          </div>
        </div>
      </div>
      <div style="flex: 4; overflow: auto">
        <div class="list-tickets">
          <ul id="lTickets" class="list-tickets">
          </ul>
        </div>
      </div>
    </div>
    <!--
    <div class="container">
      <div class="aside-info">



      </div>
    </div>
    -->
  </div>
</div>

<script>
  window.onload = function () {
    var checkedPlaces = @Json.Serialize(Model.Item2.Select(x => x.PlaceId));

    checkedPlaces.forEach((x) => {
      var el = document.getElementById(x);
      el.classList.value = "seat";

      for (let i = 0; i < el.children.length; i++) {
        el.children[0].children[i].style.fill = "#fff";
      }
      el.children[1].style.fill = "#fff";
    });

  }
</script>

<script>

  const priceForPlace = (row) => {
    var rowN = Number(row);

    console.log(rowN);

    var coef = @(3);
    switch (rowN) {
    case 1:
        return 10 * coef;
      case 2:
        return 10 * coef;
      case 3:
        return 30 * coef;
      case 4:
        return 40 * coef;
      case 5:
        return 50 * coef;
      case 6:
        return 30 * coef;
      case 7:
        return 30 * coef;
      case 8:
        return 30 * coef;
      default:
        return 30 * coef;
    }
  }

  const seatEventHandler = (seat) => {

    let splitedSeat = seat.id.split("_")
    const seatObj = { place: splitedSeat[1], row: splitedSeat[3] }

    seat.querySelectorAll('rect').
      forEach(rect => {
        rect.setAttribute('style', 'fill:#fff');
      });
    seat.querySelectorAll('path').
      forEach(path => {
        path.setAttribute('style', 'fill:#fff');
      });

    var node = document.createElement("LI");
    node.setAttribute("data-row", seatObj.row);
    node.setAttribute("data-place", seatObj.place);


    var divCard = document.createElement("DIV");
    divCard.classList.add("card");
    divCard.classList.add("blue-grey");
    divCard.classList.add("darken-4");
    divCard.classList.add("ticket-to-buy");

    var divContent = document.createElement("DIV");
    divContent.classList.add("card-content");
    divContent.classList.add("white-text");

    var div = document.createElement("DIV");
    div.classList.add("s-hflex-start");

    var spanTicket = document.createElement("SPAN");
    spanTicket.classList.add("card-title");

    var spanNode = document.createElement("SPAN");

    var textTicket = document.createTextNode("Ticket ");
    var textnode = document.createTextNode(` Ряд ${seatObj.row};  Місце ${seatObj.place}; Ціна ${priceForPlace(seatObj.row)}грн. `);
    //
    //
    spanTicket.appendChild(textTicket);

    div.appendChild(textnode);
    divContent.appendChild(spanTicket);
    divContent.appendChild(div);

    var divAction = document.createElement("DIV");
    divAction.classList.add("card-action");
    divAction.classList.add("center");
    var button = document.createElement("button");
    button.classList.add("btn");
    button.innerHTML = "Delete ticket";
    button.addEventListener('click', function (event) {

      var toRemove = event.target.closest('LI')
      var idToRemove = ""
      idToRemove = "seat_" + toRemove.getAttribute("data-place") + "_row_" + toRemove.getAttribute("data-row");
      /*toRemove.innerHTML.split(' ').map((x,index) => {
          const seat1 = "";
          const row1 = ""
          if(index===5){
              seat = "seat_" + x
              return
          }
          if(index === 2){
              row = "_row_" + x
          }
      })
      idToRemove = (seat + row).replace(/;/gi, '');*/
      console.log(idToRemove);
      const placeToUncheck = document.getElementById(idToRemove)

      placeToUncheck.querySelectorAll('rect').
        forEach(rect => {
          rect.setAttribute('style', 'fill:#ааа');
        });
      placeToUncheck.querySelectorAll('path').
        forEach(path => {
          path.setAttribute('style', 'fill:#000');
        });
      placeToUncheck.classList.add("btn")

      toRemove.remove()

      var p = Number( document.getElementById("generalPrice").innerText);
      p -= Number(priceForPlace(toRemove.getAttribute("data-row")));
      document.getElementById("generalPrice").innerText = p;

    })

    //
    divAction.appendChild(button);


    divCard.appendChild(divContent);
    divCard.appendChild(divAction);

    node.appendChild(divCard);

    //            node.appendChild(textnode);
    //            node.appendChild(button);
    document.getElementById("lTickets").appendChild(node);

    var price = Number(document.getElementById("generalPrice").innerText);
    price += Number(priceForPlace(seatObj.row));
    document.getElementById("generalPrice").innerText = price;

  }

  const theater = document.getElementById("theatre");
  theater.addEventListener('click', function (event) {
    if (event.target.closest('.btn')) {
      var seat = event.target.closest('.btn')

      seat.classList.remove("btn")
      seatEventHandler(seat)

    }
  })

  const onSubmitTickents = () => {
    const ticketsList =
      document.querySelectorAll('#lTickets')['0'].getElementsByTagName('li');
    let result = [];
    for (var i = 0; i < ticketsList.length; i++) {
      let dataRow = ticketsList[i].getAttribute("data-row");
      let dataPlace = ticketsList[i].getAttribute("data-place");
      result.push("seat_" + dataPlace.toString() + "_row_" + dataRow.toString());
    }
    console.log('@Model.Item1.ToString()');
    var s = '@(Url.ActionLink("BuyTickets","Show"))'
    const myUrlWithParams = new URL(s);
    myUrlWithParams.searchParams.append("sessionId", '@Model.Item1.ToString()')
    result.forEach((x) => myUrlWithParams.searchParams.append("tickets", x));
    myUrlWithParams.searchParams.append("price", Number(document.getElementById("generalPrice").innerText));

    console.log(myUrlWithParams);
    window.location = myUrlWithParams.href;

  }
</script>