src/Theatrum.Web.Razor/Controllers/Admin/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers.Admin
{
    [Route("admin")]
    [Authorize(Roles = Roles.Admin)]
    public class AdminController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Theatrum.Web.Razor/Controllers/Admin/ShowsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers.Admin
{
    [Route("admin/show")]

    [Authorize(Roles = Roles.Admin)]
    public class ShowsAdminController : Controller
    {
        private readonly IShowService _showService;
        private readonly ITheatrService _theatrService;
        private readonly PaginationConfig _paginationConfig;

        public ShowsAdminController(IShowService showService,
            ITheatrService theatrService,
            IOptions<PaginationConfig> paginationConfig)
        {
            _showService = showService;
            _theatrService = theatrService;
            _paginationConfig = paginationConfig.Value;
        }

        [Route("Shows")]
        public async Task<IActionResult> Shows(ShowFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        {
            var result = await Shows(filteringAdminModel, page, nameof(Shows));
            return View(result);
        }

        private async Task<ShowFilteringAdminModel> Shows(ShowFilteringAdminModel filteringAdminModel, int page, string actionName)
        {
            if (filteringAdminModel.FilteringSettings == null)
            {
                filteringAdminModel.FilteringSettings = new ShowFilteringSettingsAdminModel();
            }

            var count = await _showService.GetAllCount(filteringAdminModel.FilteringSettings);

            var shows =
                await _showService.GetAllPaginated(filteringAdminModel.FilteringSettings,
                    _paginationConfig.PaginationAdminPageSize * (page - 1),
                    _paginationConfig.PaginationAdminPageSize);

            ShowFilteringAdminModel showsFilteringAdminModel = new ShowFilteringAdminModel()
            {
                Shows = new GenericPaginatedModel<ShowModel>()
                {
                    Models = shows,
                    Pagination = new PaginationAdminModel(count, page,
                        _paginationConfig.PaginationAdminPageSize, actionName),
                },
                FilteringSettings = filteringAdminModel.FilteringSettings,
            };
            return showsFilteringAdminModel;
        }

        [HttpGet]
        [Route("item")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var theatr = await _showService.GetById((Guid)id);
            return View(theatr);
        }

        [HttpGet]
        [Route("create")]
        public async Task<IActionResult> Create()
        {
            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));

            return View();
        }

        [HttpPost]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm]ShowModel show)
        {
            if (ModelState.IsValid)
            {
                if (show.StartDate > DateTimeOffset.Now)
                {
                    if (show.StartDate < show.EndDate)
                    {
                        await _showService.CreateOrUpdate(show);
                        return RedirectToAction(nameof(Shows));
                    }
                    else
                    {
                        ModelState.AddModelError("StartDate", "Дата початку повинна бути раніше, аніж дата кінця");
                    }
  
                }
                else
                {
                    ModelState.AddModelError("StartDate", "Дата початку повинна бути пізніше, аніж сьогоднішня дата");
                }
            }

            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));

            return View(show);
        }

        [HttpGet]
        [Route("edit")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theatr = await _showService.GetById((Guid)id);
            if (theatr == null)
            {
                return NotFound();
            }

            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));
            return View(theatr);
        }

        [HttpPost]
        [Route("edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [FromForm] ShowModel show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    if (show.StartDate > DateTimeOffset.Now)
                    {
                        if (show.StartDate < show.EndDate)
                        {
                            await _showService.CreateOrUpdate(show);
                            return RedirectToAction(nameof(Shows));
                        }
                        else
                        {
                            ModelState.AddModelError("StartDate", "Дата початку повинна бути раніше, аніж дата кінця");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("StartDate", "Дата початку повинна бути пізніше, аніж сьогоднішня дата");
                    }
                }
            }
            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));
            return View(show);
        }

        [HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var show = await _showService.GetById((Guid)id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        [HttpPost, Route("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _showService.DeleteById((Guid)id);
            return RedirectToAction(nameof(Shows));
        }
    }
}

src/Theatrum.Web.Razor/Controllers/TheaterController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;

namespace Theatrum.Web.Razor.Controllers
{
    public class TheaterController : Controller
    {
        private readonly ITheatrService _theatrService;
        private readonly PaginationConfig _paginationConfig;

        public TheaterController(ITheatrService theatrService,
            IOptions<PaginationConfig> paginationConfig)
        {
            _theatrService = theatrService;
            _paginationConfig = paginationConfig.Value;
        }

        public async Task<IActionResult> Index(TheatrFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        {
            var result = await Theatrs(filteringAdminModel, page, nameof(Index));
            return View(result);
        }

        private async Task<TheatrFilteringAdminModel> Theatrs(TheatrFilteringAdminModel filteringAdminModel, int page, string actionName)
        {
            if (filteringAdminModel.FilteringSettings == null)
            {
                filteringAdminModel.FilteringSettings = new TheatrFilteringSettingsAdminModel();
            }

            var count = await _theatrService.GetAllCount(filteringAdminModel.FilteringSettings);

            var theatrs =
                await _theatrService.GetAllPaginated(filteringAdminModel.FilteringSettings,
                    _paginationConfig.PaginationAdminPageSize * (page - 1),
                    _paginationConfig.PaginationAdminPageSize);

            TheatrFilteringAdminModel theatrsFilteringAdminModel = new TheatrFilteringAdminModel()
            {
                Theatrs = new GenericPaginatedModel<TheatrModel>()
                {
                    Models = theatrs,
                    Pagination = new PaginationAdminModel(count, page,
                        _paginationConfig.PaginationAdminPageSize, actionName),
                },
                FilteringSettings = filteringAdminModel.FilteringSettings,
            };
            return theatrsFilteringAdminModel;
        }
    }
}

src/Theatrum.Web.Razor/Controllers/UserOfficeController.cs
using System.Linq;
using System.Threading.Tasks;

using Mapster;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using Theatrum.Entities.Entities;
using Theatrum.Models.Models;
using Theatrum.Utils;
using Theatrum.Web.Razor.Models;

namespace Theatrum.Web.Razor.Controllers
{
    [Authorize]
    public class UserOfficeController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public UserOfficeController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            AppUser user = (await _userManager.FindByNameAsync(User?.Identity?.Name));
            return View(user.Adapt<AppUser, AppUserModel>());
        }

        public async Task<IActionResult> UpdateProfile(AppUserModel appUserModel)
        {
            AppUser user = (await _userManager.FindByNameAsync(User?.Identity?.Name));
            var updatedUser = appUserModel.Adapt(user);
            await _userManager.UpdateAsync(updatedUser);
            if (string.IsNullOrEmpty(appUserModel.NewPassword))
            {
                return RedirectToAction(nameof(Index));
            }
            if (appUserModel.NewPassword != appUserModel.ConfirmNewPassword)
            {
                return NoContent();
            }
            await _userManager.ChangePasswordAsync(updatedUser, appUserModel.OldPassword, appUserModel.NewPassword);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Theatrum.Web.Razor/Views/Shared/_Layout.cshtml
@using Theatrum.Utils
<!DOCTYPE html>
<html>
<head>
  <title>Theatrum | @ViewData["Title"]</title>
  @{ var s = String.Join(",", (((ViewData["Meta.keywords"] ?? new string[]{ }) as string[]) ?? Array.Empty<string>()).ToList());}

  <meta name="keywords" content="@Html.Raw(s)" />
  <meta name="description" content="@(ViewData["Meta.description"])" />
  <meta name="copyright" content="&copy; 2021 - Theatrum" />


  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" media="screen,projection" />

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="./startup.js"></script>
  <link rel="stylesheet" href="~/css/main.css">
  <link rel="stylesheet" href="~/css/common.css">
  <link rel="stylesheet" href="~/css/indentations.css">
</head>
<body>

  <header id="Headertoinclude">
    <nav class="grey darken-4">
      <div class="container">
        <div class="nav-wrapper">
          <ul class="left">
            <li>
              <a href="#" data-target="side-navigation" class="sidenav-trigger" style="display: block; margin: 0px;"><i class="material-icons">menu</i></a>
            </li>
          </ul>
          <a asp-action="Index" asp-controller="Home" class="brand-logo center">Theatrum</a>
          <ul id="nav-mobile" class="right">
            @if (!User.Identity.IsAuthenticated)
            {

              <li class="uppercase weight-normal">
                <a asp-controller="Account" asp-action="Login">
                  <i class="material-icons right">person</i>Авторизуватися
                </a>
              </li>

              <li class="weight-normal">
                <a asp-area="" asp-controller="Account" asp-action="Register">Зареєструватися</a>
              </li>
            }
            else
            {
              <li class="uppercase weight-normal">
                <a asp-controller="UserOffice" asp-action="Index">
                  <i class="material-icons right">person</i>@User.Identity.Name
                </a>
              </li>
              <li class="weight-normal">
                <a asp-area="" asp-controller="Account" asp-action="Logout">Вийти</a>
              </li>
            }
          </ul>
        </div>
      </div>
    </nav>
  </header>


  <main class="grey darken-3 white-text">
    <ul id="side-navigation" class="sidenav grey darken-3 pt15">
      <li>
        <div href="#" class="s-hflex" style="padding: 0 32px;">
          <div class="equal-flex">
            <a href="#" class="brand-logo center weight-strong white-text">Theatrum</a>
          </div>
          <div class="s-vflex-center">
            <a class="sidenav-close s-vflex-center white-text" href="#!"><i class="material-icons small">close</i></a>
          </div>
        </div>
      </li>
      <li>
        <div class="divider black"></div>
      </li>
      <li>
        <a style="font-size: 20px;" asp-controller="Home" asp-action="Index">Вистави</a>
      </li>
      <li>
        <a style="font-size: 20px;" asp-controller="Theater" asp-action="Index">Театри</a>
      </li>
      <li>
        <div class="divider black"></div>
      </li>
      @if (!User.IsInRole(Roles.Admin))
      {
        <li>
          <a style="font-size: 20px;" asp-area="" asp-controller="Account" asp-action="Login">Увійти</a>
        </li>
        <li>
          <a style="font-size: 20px;" asp-area="" asp-controller="Account" asp-action="Register">Зареєструватися</a>
        </li>
      }
      @if (User.IsInRole(Roles.Admin))
      {
        <li>
          <a style="font-size: 20px;" asp-controller="Admin" asp-action="Index">Сторінка адміністратора</a>
        </li>
      }
      @if (User.Identity.IsAuthenticated)
      {
        <li><a style="font-size: 20px;" asp-area="" asp-controller="Account" asp-action="Logout"><i class="material-icons small">directions_run</i>Вийти</a></li>
      }
      @*<li style="padding: 10px 32px;">
        <div class="s-hflex">
            <a href="#" class="tooltipped white-text" data-position="top" data-tooltip="About"><i class="material-icons small">info_outline</i></a>
            <a href="#" class="tooltipped white-text" data-position="top" data-tooltip="Help"><i class="material-icons small">help_outline</i></a>
        </div>
    </li>*@
    </ul>
    <div class="container">
      <div class="row">
        @RenderBody()
      </div>
    </div>
  </main>

  <footer id="FooterToinclude" class="page-footer p0 grey darken-4 z-depth-4">
    <div class="footer-copyright">
      <div class="container">
        <div class="container">
          &copy; 2021 - Theatrum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
      </div>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/materialize/js/materialize.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Theatrum.Web.Razor/Views/Shared/_LayoutAdminPages.cshtml
@using Theatrum.Utils
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Theatrum | @ViewData["Title"]</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Theatrum.Web.Razor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна (для користувача)</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Головна (Адмін частина)</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="TheatersAdmin" asp-action="Index">Театри</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="ShowsAdmin" asp-action="Shows">Вистави</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="UsersAdmin" asp-action="Index">Користувачі</a>
            </li>

          </ul>
          <ul class="navbar-nav mr-auto">
            @if (User.Identity.IsAuthenticated)
            {
              <li class="nav-item">
                <a class="nav-link text-dark left" asp-area="" asp-controller="Account" asp-action="Logout">Вийти</a>
              </li>
            }
            else
            {

              <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
              </li>
            }
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2021 - Theatrum.Web.Razor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Theatrum.Web.Razor/Views/Shared/_PaginationPartial.cshtml
@model Theatrum.Models.Admin.PaginationAdminModel

<div class="col s12">
  <ul class="pagination center">
    @if (Model.HasPrevious)
    {
      <li class="waves-effect">
        <a asp-action=@(Model.Action) 
           asp-controller=@(Model.Controller) 
           asp-route-page=@(Model.PageNumber-1)
           class="white-text">
          <i class="material-icons">chevron_left</i>
        </a>
      </li>
    }
    else
    {
      <li class="disabled">
        <a>
          <i class="material-icons">chevron_left</i>
        </a>
      </li>

    }
    
    @for (int i = 1; i <= Model.Total; i++)
    {
      if (Model.PageNumber == i)
      {
        <li class="active pagination-bg">
          <a asp-action=@(Model.Action) 
             asp-controller=@(Model.Controller) 
             asp-route-page=@i
             class="white-text">
            @i
          </a>
        </li>
      }
      else
      {
        <li class="waves-effect">
          <a asp-action=@(Model.Action) 
             asp-controller=@(Model.Controller) 
             asp-route-page=@i
             class="white-text">
            @i
          </a>
        </li>
      }
    }
    @if (Model.HasPrevious)
    {
      <li class="waves-effect">
        <a asp-action=@(Model.Action) 
           asp-controller=@(Model.Controller) 
           asp-route-page=@(Model.PageNumber+1)
           class="white-text">
          <i class="material-icons">chevron_right</i>
        </a>
      </li>
    }
    else
    {
      <li class="disabled">
        <a class="white-text">
          <i class="material-icons">chevron_right</i>
        </a>
      </li>

    }
  </ul>
</div>