src/Theatrum.Web.Razor/Controllers/Admin/ShowsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers.Admin
{
    [Route("admin/show")]

    [Authorize(Roles = Roles.Admin)]
    public class ShowsAdminController : Controller
    {
        private readonly IShowService _showService;
        private readonly ITheatrService _theatrService;
        private readonly PaginationConfig _paginationConfig;

        public ShowsAdminController(IShowService showService,
            ITheatrService theatrService,
            IOptions<PaginationConfig> paginationConfig)
        {
            _showService = showService;
            _theatrService = theatrService;
            _paginationConfig = paginationConfig.Value;
        }

        [Route("Shows")]
        public async Task<IActionResult> Shows(ShowFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        {
            var result = await Shows(filteringAdminModel, page, nameof(Shows));
            return View(result);
        }

        private async Task<ShowFilteringAdminModel> Shows(ShowFilteringAdminModel filteringAdminModel, int page, string actionName)
        {
            if (filteringAdminModel.FilteringSettings == null)
            {
                filteringAdminModel.FilteringSettings = new ShowFilteringSettingsAdminModel();
            }

            var count = await _showService.GetAllCount(filteringAdminModel.FilteringSettings);

            var shows =
                await _showService.GetAllPaginated(filteringAdminModel.FilteringSettings,
                    _paginationConfig.PaginationAdminPageSize * (page - 1),
                    _paginationConfig.PaginationAdminPageSize);

            ShowFilteringAdminModel showsFilteringAdminModel = new ShowFilteringAdminModel()
            {
                Shows = new GenericPaginatedModel<ShowModel>()
                {
                    Models = shows,
                    Pagination = new PaginationAdminModel(count, page,
                        _paginationConfig.PaginationAdminPageSize, actionName),
                },
                FilteringSettings = filteringAdminModel.FilteringSettings,
            };
            return showsFilteringAdminModel;
        }

        [HttpGet]
        [Route("item")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var theatr = await _showService.GetById((Guid)id);
            return View(theatr);
        }

        [HttpGet]
        [Route("create")]
        public async Task<IActionResult> Create()
        {
            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));

            return View();
        }

        [HttpPost]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm]ShowModel show)
        {
            if (ModelState.IsValid)
            {
                if (show.StartDate > DateTimeOffset.Now)
                {
                    if (show.StartDate < show.EndDate)
                    {
                        await _showService.CreateOrUpdate(show);
                        return RedirectToAction(nameof(Shows));
                    }
                    else
                    {
                        ModelState.AddModelError("StartDate", "Дата початку повинна бути раніше, аніж дата кінця");
                    }
  
                }
                else
                {
                    ModelState.AddModelError("StartDate", "Дата початку повинна бути пізніше, аніж сьогоднішня дата");
                }
            }

            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));

            return View(show);
        }

        [HttpGet]
        [Route("edit")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theatr = await _showService.GetById((Guid)id);
            if (theatr == null)
            {
                return NotFound();
            }

            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));
            return View(theatr);
        }

        [HttpPost]
        [Route("edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [FromForm] ShowModel show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    if (show.StartDate > DateTimeOffset.Now)
                    {
                        if (show.StartDate < show.EndDate)
                        {
                            await _showService.CreateOrUpdate(show);
                            return RedirectToAction(nameof(Shows));
                        }
                        else
                        {
                            ModelState.AddModelError("StartDate", "Дата початку повинна бути раніше, аніж дата кінця");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("StartDate", "Дата початку повинна бути пізніше, аніж сьогоднішня дата");
                    }
                }
            }
            var theatersForSelect = await _theatrService.GetAllForSelect();
            ViewBag.TheatrumId = theatersForSelect.Select(x => new SelectListItem(x.Item2, x.Item1.ToString()));
            return View(show);
        }

        [HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var show = await _showService.GetById((Guid)id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        [HttpPost, Route("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _showService.DeleteById((Guid)id);
            return RedirectToAction(nameof(Shows));
        }
    }
}

src/Theatrum.Web.Razor/Controllers/PhotoController.cs
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

using Theatrum.Bl.Abstract.IServices;
using Theatrum.Models.Models;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers
{
    [Route("photo")]
    public class PhotoController : Controller
    {
        private readonly IPhotoService _photoService;
        private readonly IWebHostEnvironment _env;

        public PhotoController(IPhotoService photoService,
            IWebHostEnvironment env)
        {
            _photoService = photoService;
            _env = env;
        }

        [HttpGet]
        [Route("AdminPhoto/{photoId}")]
        public async Task<FileResult> AdminPhoto(Guid? photoId)
        {
            if (photoId == null || photoId == Guid.Empty)
            {
                return await DefaultPhoto();
            }
            PhotoModel photo = await _photoService.GetPhoto((Guid)photoId);
            var filePath = Path.Combine(
                _env.ContentRootPath, Settings.UploadDirectory, photo.Name);
            if (!System.IO.File.Exists(filePath))
            {
                return await DefaultPhoto();
            }
            return PhysicalFile(filePath, photo.ContentType);

        }

        public async Task<FileResult> DefaultPhoto()
        {
            var filePath = Path.Combine(
                _env.ContentRootPath, Settings.UploadDirectory, "default.jpg");
            return PhysicalFile(filePath, "image/jpg");
        }

    }
}

src/Theatrum.Web.Razor/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using QRCoder;
using Theatrum.Bl.Abstract.IServices;
using Theatrum.Dal.Impl.Postgres;
using Theatrum.Entities.Entities;
using Theatrum.Models.Admin;
using Theatrum.Models.Models;
using Theatrum.Models.Settings;
using Theatrum.Utils;

namespace Theatrum.Web.Razor.Controllers
{
    [Route("show")]
    public class ShowsController : Controller
    {
        private readonly IShowService _showService;
        private readonly UserManager<AppUser> _userManager;
        private readonly PaginationConfig _paginationConfig;

        public ShowsController(IShowService showService,
            IOptions<PaginationConfig> paginationConfig,
            UserManager<AppUser> userManager)
        {
            _showService = showService;
            _userManager = userManager;
            _paginationConfig = paginationConfig.Value;
        }

        //public async Task<IActionResult> Shows(ShowFilteringAdminModel filteringAdminModel, [FromQuery] int page = 1)
        //{
        //    var result = await Shows(filteringAdminModel, page, nameof(Shows));
        //    return View(result);
        //}

        //private async Task<ShowFilteringAdminModel> Shows(ShowFilteringAdminModel filteringAdminModel, int page, string actionName)
        //{
        //    if (filteringAdminModel.FilteringSettings == null)
        //    {
        //        filteringAdminModel.FilteringSettings = new ShowFilteringSettingsAdminModel();
        //    }

        //    var count = await _showService.GetAllCount(filteringAdminModel.FilteringSettings);

        //    var shows =
        //        await _showService.GetAllPaginated(filteringAdminModel.FilteringSettings,
        //            _paginationConfig.PaginationAdminPageSize * (page - 1),
        //            _paginationConfig.PaginationAdminPageSize);

        //    ShowFilteringAdminModel showsFilteringAdminModel = new ShowFilteringAdminModel()
        //    {
        //        Shows = new GenericPaginatedModel<ShowModel>()
        //        {
        //            Models = shows,
        //            Pagination = new PaginationAdminModel(count, page,
        //                _paginationConfig.PaginationAdminPageSize, actionName),
        //        },
        //        FilteringSettings = filteringAdminModel.FilteringSettings,
        //    };
        //    return showsFilteringAdminModel;
        //}

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Details([FromRoute] Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var theatr = await _showService.GetById((Guid)id);
            return View(theatr);
        }


        [HttpGet]
        [Authorize]
        [Route("tickets/{id}")]
        public async Task<IActionResult> Tickets([FromRoute] Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            List<PlaceModel> places = await _showService.GetPlacesBySessionId((Guid)id);
            return View(((Guid)id,places));
        }

        [Authorize]
        [Route("BuyTickets")]
        public async Task<IActionResult> BuyTickets(Guid sessionId, List<string> tickets, int price)
        {
            // Guid userId = (await _userManager.FindByNameAsync(User?.Identity?.Name)).Id;
            // List<PlaceModel> result = await _showService.CreateTickets(tickets, userId, sessionId);
            // for (int i = 0; i < result.Count; i++)
            // {
            //     result[i].QrCode = await GetQrCode(result[i].SecurityKey.ToString(), Color.Black);
            // }
            return View((sessionId,tickets, price));
        }

        [Authorize]
        [Route("BoughtTicket")]
        public async Task<IActionResult> BoughtTickets(Guid sessionId, List<string> tickets, [Required]string card, [Required]string date, [Required]string cvv)
        {
            Guid userId = (await _userManager.FindByNameAsync(User?.Identity?.Name)).Id;
            List<PlaceModel> result = await _showService.CreateTickets(tickets, userId, sessionId);
            return View(result);
        }

        public async Task<Byte[]> GetQrCode(string qrCodeText, Color color)
        {
            // using static method as instance method was just redirection to static one
            QRCodeData qrCodeData = QRCodeGenerator.GenerateQrCode(qrCodeText, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(4);
            if (color != Color.Black)
            {
                qrCodeImage = ChangeColor(qrCodeImage, color);
            }
            return BitmapToBytes(qrCodeImage);
        }

        private static Byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }

        private Bitmap ChangeColor(Bitmap scrBitmap, Color newColor)
        {
            // make an empty bitmap the same size as scrBitmap  
            Bitmap newBitmap = new Bitmap(scrBitmap.Width, scrBitmap.Height);
            for (int i = 0; i < scrBitmap.Width; i++)
            {
                for (int j = 0; j < scrBitmap.Height; j++)
                {
                    // get the pixel from the scrBitmap image  
                    var actualColor = scrBitmap.GetPixel(i, j);

                    // invert colors, since we want to tint the dark parts and not the bright ones
                    var invertedOriginalR = 255 - actualColor.R;
                    var invertedOriginalG = 255 - actualColor.G;
                    var invertedOriginalB = 255 - actualColor.B;

                    // multiply source by destination color (as float channels)
                    int r = (invertedOriginalR / 255) * (newColor.R / 255) * 255;
                    int g = (invertedOriginalG / 255) * (newColor.G / 255) * 255;
                    int b = (invertedOriginalB / 255) * (newColor.B / 255) * 255;
                    var tintedColor = Color.FromArgb(r, g, b);
                    newBitmap.SetPixel(i, j, tintedColor);
                }
            }
            return newBitmap;
        }
    }
}

src/Theatrum.Web.Razor/Views/ShowsAdmin/Create.cshtml
@model Theatrum.Models.Models.ShowModel

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutAdminPages";
}


<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="Create" enctype="multipart/form-data">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="TheatrumId" class="control-label"></label>
        <select asp-for="TheatrumId" class="form-control" asp-items="ViewBag.TheatrumId"></select>
      </div>
      <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="StartDate" class="control-label"></label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="EndDate" class="control-label"></label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="AgeLimitation" class="control-label"></label>
        <input asp-for="AgeLimitation" class="form-control" />
        <span asp-validation-for="AgeLimitation" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="ShowPhoto" class="control-label"></label>
        <input asp-for="ShowPhoto" type="file" />
      </div>
      <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
      </div>
    </form>
  </div>
</div>

<div>
  <a asp-action="Shows">Back to List</a>
</div>

@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Theatrum.Web.Razor/Views/ShowsAdmin/Delete.cshtml
@model Theatrum.Models.Models.ShowModel

@{
  ViewData["Title"] = "Delete";
  Layout = "_LayoutAdminPages";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
  <h4>Show</h4>
  <hr />
  <dl class="row">
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.TheatrumId)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.TheatrumId)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Description)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.StartDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.StartDate)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.EndDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.EndDate)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.PhotoId)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.PhotoId)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.AgeLimitation)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.AgeLimitation)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.ShowPhoto)
    </dt>
    <dd class="col-sm-10">
      @if (Model.PhotoId != null)
      {
        <img class="image-small render-photo" src="@(@Url.ActionLink("AdminPhoto", "Photo", new {photoId = Model.PhotoId}))" name=@Html.Raw(@Url.Action("AdminPhoto", "Photo", new {photoId = Model.PhotoId})) />
      }
    </dd>
  </dl>

  <form asp-action="DeleteConfirmed">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Shows">Back to List</a>
  </form>
</div>

src/Theatrum.Web.Razor/Views/ShowsAdmin/Details.cshtml
@model Theatrum.Models.Models.ShowModel

@{
  Layout = "_LayoutAdminPages";
  ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
  <h4>Show</h4>
  <hr />
  <dl class="row">
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.TheatrumId)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.TheatrumId)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Description)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.StartDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.StartDate)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.EndDate)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.EndDate)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.PhotoId)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.PhotoId)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.AgeLimitation)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.AgeLimitation)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.ShowPhoto)
    </dt>
    <dd class="col-sm-10">
      @if (Model.PhotoId != null)
      {
        <img class="image-small render-photo" src="@(@Url.ActionLink("AdminPhoto", "Photo", new {photoId = Model.PhotoId}))" name=@Html.Raw(@Url.Action("AdminPhoto", "Photo", new {photoId = Model.PhotoId})) />
      }
    </dd>
  </dl>
</div>

<div>
  <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
  <a asp-action="Shows">Back to List</a>
</div>

src/Theatrum.Web.Razor/Views/ShowsAdmin/Edit.cshtml
@model Theatrum.Models.Models.ShowModel

@{
  Layout = "_LayoutAdminPages";
  ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Show</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="Edit" enctype="multipart/form-data">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <input type="hidden" asp-for="Id" />
      <div class="form-group">
        <label asp-for="TheatrumId" class="control-label"></label>
        <select asp-for="TheatrumId" class="form-control" asp-items="ViewBag.TheatrumId"></select>
        <span asp-validation-for="TheatrumId" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control" ></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="StartDate" class="control-label"></label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="EndDate" class="control-label"></label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="PhotoId" class="control-label"></label>
        <input asp-for="PhotoId" class="form-control" />
        <span asp-validation-for="PhotoId" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="AgeLimitation" class="control-label"></label>
        <input asp-for="AgeLimitation" class="form-control" />
        <span asp-validation-for="AgeLimitation" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="ShowPhoto" class="control-label"></label>
        <input asp-for="ShowPhoto" type="file" />
      </div>
      <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
      </div>
    </form>
  </div>
</div>

<div>
  <a asp-action="Shows">Back to List</a>
</div>

@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Theatrum.Web.Razor/Views/ShowsAdmin/Shows.cshtml
@using Theatrum.Entities.Entities
@model Theatrum.Models.Admin.ShowFilteringAdminModel

@{
  Layout = "_LayoutAdminPages";
  ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="ShowsAdmin" asp-action="Shows" method="post">
  <div class="form-group row">
    <label asp-for="FilteringSettings.Name" class="col-sm-1 col-form-label">Name</label>
    <div class="col-sm-3">
      <input asp-for="FilteringSettings.Name" class="form-control" />
    </div>
    <label asp-for="FilteringSettings.TheatrId" class="col-sm-1 col-form-label">TheatrId</label>
    <div class="col-sm-3">
      <input asp-for="FilteringSettings.TheatrId" class="form-control" />
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </div>
</form>

<p>
  <a asp-action="Create">Create New</a>
</p>
@if (Model.Shows.Models.Count != 0)
{
  <table class="table">
    <thead>
      <tr>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].TheatrumId)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].Name)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].Description)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].StartDate)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].EndDate)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Shows.Models[0].AgeLimitation)
        </th>
        <th>
          Photo
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model.Shows.Models)
      {
        <tr>
          <td>
            @Html.DisplayFor(modelItem => item.TheatrumId)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.Name)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.Description)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.StartDate)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.EndDate)
          </td>
          <td>
            @Html.DisplayFor(modelItem => item.AgeLimitation)+
          </td>
          <td>
            @if (item.PhotoId != null)
            {
              <img class="image-small render-photo" src="@(@Url.ActionLink("AdminPhoto", "Photo", new {photoId = @item.PhotoId}))" name=@Html.Raw(@Url.Action("AdminPhoto", "Photo", new {photoId = @item.PhotoId}))/>
            }
          </td>
          <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
          </td>
        </tr>
      }
    </tbody>
  </table>
}